# Generated by Django 4.0.4 on 2022-06-07 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='organization',
            name='foundationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='organization',
            name='registryDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='voluntary',
            name='ageOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='voluntary',
            name='registryDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
