# Generated by Django 4.0.4 on 2022-06-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_enddate_event_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntary_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
                ('voluntaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voluntary')),
            ],
        ),
    ]
