# Generated by Django 4.0.4 on 2022-06-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntary_events',
            name='organizationId',
        ),
        migrations.AddField(
            model_name='voluntary_events',
            name='eventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
            preserve_default=False,
        ),
    ]
