# Generated by Django 4.0.4 on 2022-06-07 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgImg', models.ImageField(default='blank-profile-picture.png', upload_to='organization_images')),
                ('orgName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contactNumber', models.IntegerField(default=0)),
                ('websiteAddress', models.CharField(max_length=250)),
                ('foundationDate', models.DateField(default=datetime.date.today)),
                ('registryDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', models.ImageField(default='blank-profile-picture.png', upload_to='voluntary_images')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('registryDate', models.DateField(default=datetime.date.today)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('ageOfBirth', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntary_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
                ('voluntaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voluntary')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventMainImage', models.ImageField(default='event-default.png', upload_to='events_images')),
                ('eventName', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=1000)),
                ('totalVoluntarys', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=8)),
                ('district', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('idOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
            ],
        ),
    ]
