# Generated by Django 4.0.4 on 2022-06-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hours',
            field=models.IntegerField(default=1),
        ),
    ]
